"""Production DAILY V2 publish + deliver CLI -- the PRODUCTION DAILY Kakao
path (quality-hardening phase). Runs the full REQUIRED daily flow:

    verify local docs/v2/ (already generated by generate_daily_web_report_v2.py)
    -> publish (git commit+push, exact files only)          [blocks Kakao on failure]
    -> verify the real external public pages                [blocks Kakao on failure]
    -> exactly ONE Kakao message (report_delivery_v2.deliver_daily_summary_v2)
    -> REQUIRED post-send report.publication_consistency check

    .venv\\Scripts\\python.exe scripts\\publish_and_deliver_v2.py [--report-date YYYY-MM-DD] [--no-push]

Never regenerates the dashboard itself (that's scripts/generate_daily_web_
report_v2.py's own job, upstream of this CLI in the daily pipeline) and
never calls V1's sender (scripts/deliver_daily_report.py) -- V1 remains
completely untouched and usable for manual/rollback purposes, it is simply
never invoked by this path. --no-push is for local/test verification only
(commits locally but never pushes) -- a real daily run always pushes.

Exit code contract:
  0 = overall status PASS (every gate passed, including the required
      post-send consistency check) -- includes a legitimate duplicate-send
      skip (idempotency working as intended, not an error)
  1 = any gate failed (PUBLISH_BLOCKED / PUBLISH_FAILED /
      EXTERNAL_VERIFICATION_FAILED / KAKAO_SEND_FAILED /
      POST_SEND_CONSISTENCY_FAILED), or a global run-start failure
  2 = CLI invocation error (argparse's own handling)
"""

import argparse
import logging
import secrets
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import logging_setup
from config import DB_PATH
from db.database import connect, init_db
from ingestion.orchestrator import GlobalFailureError, finalize_run, start_run
from report.release_v2 import ReleaseStatus, run_daily_v2_release

logger = logging.getLogger(__name__)

EXIT_OK = 0
EXIT_RELEASE_FAILURE = 1
EXIT_CONFIG_ERROR = 2

_KST = timezone(timedelta(hours=9))

# Repo root (ai-playground/), a sibling of super-news/scripts/../.. --
# same resolution convention scripts/generate_daily_web_report_v2.py's own
# _DOCS_V2_DIR already uses.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_DOCS_V2_DIR = _REPO_ROOT / "docs" / "v2"


def _generate_run_id():
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    suffix = secrets.token_hex(3)
    return f"daily-publish-deliver-v2-{timestamp}-{suffix}"


def _parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Publish today's SUPER NEWS V2.1 dashboard and deliver the one real daily Kakao summary."
    )
    parser.add_argument("--db-path", type=Path, default=None,
                         help="Override the SQLite DB path (default: the project's configured data/super_news.db).")
    parser.add_argument("--report-date", type=str, default=None,
                         help="KST report date YYYY-MM-DD (default: today, KST).")
    parser.add_argument("--docs-dir", type=Path, default=None,
                         help="Override the docs/v2/ directory (test isolation only).")
    parser.add_argument("--repo-root", type=Path, default=None,
                         help="Override the repo root for git operations (test isolation only).")
    parser.add_argument("--no-push", action="store_true",
                         help="Commit locally but never push -- local/test verification only; "
                              "a real daily run always pushes.")
    return parser.parse_args(argv)


def main(argv=None):
    logging_setup.setup_logging()
    args = _parse_args(argv)

    db_path = args.db_path if args.db_path is not None else DB_PATH
    docs_dir = args.docs_dir if args.docs_dir is not None else _DOCS_V2_DIR
    repo_root = args.repo_root if args.repo_root is not None else _REPO_ROOT
    run_id = _generate_run_id()
    report_date_kst = args.report_date or datetime.now(_KST).strftime("%Y-%m-%d")

    init_db(db_path=db_path)
    conn = connect(db_path=db_path)
    try:
        try:
            runs_row_id = start_run(conn, run_id, report_date_kst, registry_hash=None)
        except GlobalFailureError as exc:
            logger.error("run_id=%s global failure: %s", run_id, type(exc).__name__)
            print(f"Run failed before/without completing: {exc}")
            return EXIT_RELEASE_FAILURE

        result = run_daily_v2_release(
            conn, report_date_kst, docs_dir, repo_root, runs_row_id,
            push=not args.no_push,
        )
        final_status = finalize_run(
            conn, runs_row_id,
            [{"source_name": "publish_and_deliver_v2", "category": "DAILY_V2_RELEASE",
              "status": "SUCCESS" if result["status"] == ReleaseStatus.PASS_ else "FAILED"}],
        )
    finally:
        conn.close()

    print(f"run_id={run_id} report_date={report_date_kst} run_status={final_status}")
    print(f"  release_status={result['status']}")
    if result["reason"]:
        print(f"  reason={result['reason']}")
    if result["delivery"]:
        print(f"  kakao_delivery_status={result['delivery']['status']}")
    if result["consistency"]:
        print(f"  publication_consistency={result['consistency']['status']}")

    return EXIT_OK if result["status"] == ReleaseStatus.PASS_ else EXIT_RELEASE_FAILURE


if __name__ == "__main__":
    sys.exit(main())
