"""SUPER NEWS MUSIC / SUPER NEWS DAILY product-page publish CLI (ADDED
2026-08-19, production incident follow-up -- see report/release_v2.py's
own product-page release gate section docstring). Runs the REQUIRED web
flow for docs/v2/music.html and docs/v2/daily.html -- the pages the real
Kakao MUSIC/DAILY sends actually link to (report_delivery_v2._resolve_v2_
link_url):

    verify local docs/v2/music.html + docs/v2/daily.html (already
    generated by generate_daily_web_report_v2.py, upstream of this CLI)
    -> publish (git commit+push, exact files only)   [blocks external verify on failure]
    -> verify the real external public pages

    .venv\\Scripts\\python.exe scripts\\publish_v2_product_pages.py [--report-date YYYY-MM-DD] [--no-push]

DELIBERATELY sends NO Kakao message -- report_delivery_v2.deliver_music_
digest_v2/deliver_daily_digest_v2 (scripts/run_daily_kakao_delivery_v2.py)
is the real, already-idempotent production Kakao path and runs as its own
SEPARATE stage after this one in scripts/run_daily_full_pipeline_v2.py.
Never regenerates the pages themselves (that is scripts/
generate_daily_web_report_v2.py's own job, upstream of this CLI) and never
touches docs/v2/index.html or docs/v2/reports/ (that pair stays
report.release_v2.publish_v2_dashboard's own exclusive scope).

Exit code contract:
  0 = overall status PASS (local verify + publish + external verify all
      passed)
  1 = any gate failed (PUBLISH_BLOCKED / PUBLISH_FAILED /
      EXTERNAL_VERIFICATION_FAILED)
  2 = CLI invocation error (argparse's own handling)
"""

import argparse
import logging
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import logging_setup
from report.release_v2 import ReleaseStatus, run_daily_v2_product_pages_publish

logger = logging.getLogger(__name__)

EXIT_OK = 0
EXIT_RELEASE_FAILURE = 1
EXIT_CONFIG_ERROR = 2

_KST = timezone(timedelta(hours=9))

# Repo root (ai-playground/), a sibling of super-news/scripts/../.. -- same
# resolution convention scripts/generate_daily_web_report_v2.py's own
# _DOCS_V2_DIR / scripts/publish_and_deliver_v2.py's own _REPO_ROOT use.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_DOCS_V2_DIR = _REPO_ROOT / "docs" / "v2"


def _parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Publish today's SUPER NEWS MUSIC / SUPER NEWS DAILY product pages (no Kakao send)."
    )
    parser.add_argument("--db-path", type=Path, default=None,
                         help="Accepted for CLI-shape uniformity with every other pipeline stage script "
                              "(scripts/run_daily_full_pipeline_v2.py's own _run_stage always passes "
                              "--db-path to every stage) -- unused: this CLI only reads already-generated "
                              "HTML files and never touches the database.")
    parser.add_argument("--report-date", type=str, default=None,
                         help="KST report date YYYY-MM-DD (default: today, KST).")
    parser.add_argument("--docs-dir", type=Path, default=None,
                         help="Override the docs/v2/ directory (test isolation only).")
    parser.add_argument("--repo-root", type=Path, default=None,
                         help="Override the repo root for git operations (test isolation only).")
    parser.add_argument("--no-push", action="store_true",
                         help="Commit locally but never push -- local/test verification only; "
                              "a real daily run always pushes.")
    return parser.parse_args(argv)


def main(argv=None):
    logging_setup.setup_logging()
    args = _parse_args(argv)

    docs_dir = args.docs_dir if args.docs_dir is not None else _DOCS_V2_DIR
    repo_root = args.repo_root if args.repo_root is not None else _REPO_ROOT
    report_date_kst = args.report_date or datetime.now(_KST).strftime("%Y-%m-%d")

    result = run_daily_v2_product_pages_publish(
        report_date_kst, docs_dir, repo_root, push=not args.no_push,
    )

    print(f"report_date={report_date_kst} release_status={result['status']}")
    if result["reason"]:
        print(f"  reason={result['reason']}")
    if result["publish"]:
        print(f"  published={result['publish']['published']} pushed={result['publish']['pushed']}")

    return EXIT_OK if result["status"] == ReleaseStatus.PASS_ else EXIT_RELEASE_FAILURE


if __name__ == "__main__":
    sys.exit(main())
